services:
#    mrz_jobeet.example:
#        class: Mrz\JobeetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    mrz.jobeet.admin.category:
        class: Mrz\JobeetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments: [null, Mrz\JobeetBundle\Entity\Category, MrzJobeetBundle:CategoryAdmin]
 
    mrz.jobeet.admin.job:
        class: Mrz\JobeetBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments: [null, Mrz\JobeetBundle\Entity\Job, MrzJobeetBundle:JobAdmin]
